name: Release

on:
  push:
    tags:
      - 'v*.*.*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build:all
        
      - name: Build CRX file
        working-directory: './build'
        env:
          CHROMIUM_CRX_PEM: ${{ secrets.CHROMIUM_CRX_PEM }}
        run: |
          echo "$CHROMIUM_CRX_PEM" > ./crx.pem
          npx crx pack chromium -o linguist.crx -p ./crx.pem
          ls -al ./

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*.zip
            build/linguist.crx
            
      - name: Build static files for GitHub Pages
        working-directory: './build'
        run: |
          mkdir ./site
          node ../scripts/genCrxUpdateManifest.js > ./site/chromium_updates.xml
          # TODO: build index.html with landing page
      
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: noreply@example.com
          build_dir: './build/site'
          branch: gh-pages
